### PR TITLE
Added SecondChance algorithm to allow you to retry importing nodes th…

### PR DESCRIPTION
**Pull request by xydan83**
…at could not be imported because they did not find their parents. This may be the case if we have a node type of Object which has its own parent node type of Variable. For example, this could be a HasHistoricalConfiguration reference type. Also, the status about how many nodes we have imported shows numbers that include nodes that were not imported due to some error.

### CODE REVIEW

**Comment by xydan83** [comment]
Hello! I changed some details and included the container in the **addNodeImpl** function. NL_Node no longer has StatusCode. Look here please.

**Comment by xydan83** [comment]
Can you restart the tests? It is very strange that after **git push --force** to my tree I see only 2 checks instead of 5 (or 4).

**Comment by xydan83** [comment]
WindowsBuildOnly is using an old version of open62541 (open62541/1.3.1) and we are getting an error.

image

**Comment by xydan83** [comment]
Added a couple of tests.

**Comment by matkonnerth** [comment]
Thank you, good job!

**Pull request merged**
